### ISSUE TITLE
Park Map request

### ISSUE THREAD

**Issue by Nchrist89** [Nchrist89/Palms-Peaks-P1#3]
**User Story:** 
As a first-time visitor, I want to view a map of Palms and Peaks that shows rides, food locations, and accessible paths so that I can plan my visit efficiently.

**Acceptance Criteria:**

- [ ] The map is easily accessible from the homepage.
- [ ] Map shows where there is food available, paths to rides and shops. 

**Tasks:** 

- [ ] To create a page dedicated to the park itself and information about the park which will also include a map of the park and resort. 
- [ ] Make the Map accessible from the home page
