### ISSUE TITLE
Full Website Accessibility

### ISSUE THREAD

**Issue by Nchrist89** [Nchrist89/Palms-Peaks-P1#9]
**User Story:** 
As a sight-impaired user who uses a screen reader, I want the Palms and Peaks website to be fully accessible so that I can navigate it easily and obtain information about the park’s attractions, events, and services without difficulty.

**Acceptance Criteria:**

- [ ] All website content, including images and videos, includes descriptive alt text that is compatible with screen readers.
- [ ] The website uses semantic HTML and ARIA (Accessible Rich Internet Applications) landmarks to provide clear navigation and structure.
- [ ] All buttons, links, and forms are labelled clearly for screen reader users, including context for actions they can take (e.g., "Buy Tickets", "View Attractions").

**Tasks:**

- [ ] When creating website, ensure that Aria labels are implemented throughout the project and has full accessibility.
- [ ] . Final review and test to ensure accessibility using Lighthouse
